name: dom_eliseu
description: "Projeto desenvolvido na disciplina de Programação para Dispositivos Móveis"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  flex_color_picker: ^3.5.0
  flutter_chat_bubble: ^2.0.2
  emoji_picker_flutter: ^2.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/